version: '3.7'

services:
  events-web:
    container_name: events-web
    build:
      context: ./docker/nginx
      args:
        user: events
        UID: 501
    ports:
      - 350:80
    volumes:
      - ./:/var/www
    depends_on:
      - events-be
      - events-db
    networks:
      - events-network

  events-be:
    container_name: events-be
    build:
      context: ./docker/php
      args:
        user: events
        UID: 501
    environment:
      PHP_IDE_CONFIG: serverName=Docker
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9003 XDEBUG_CLIENT_HOST=host.docker.internal XDEBUG_CLIENT_PORT=9003
    volumes:
      - ./:/var/www
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ~/.ssh/id_rsa:/home/appuser/.ssh/events
    networks:
      - events-network
    depends_on:
      - events-db

  events-db:
    container_name: events-db
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=123123
      - MYSQL_USER=user
      - MYSQL_DATABASE=EventsDb
    networks:
      - events-network

networks:
  events-network:
    external: true
